# 这是 RandomBrainHole 插件的配置模板文件。
# 请根据您的实际设置填写必要的值。

# (可选) 您的数据文件（如 Excel、Word 文档）的基础存储路径。
# 这个配置主要由 import_data.py 脚本使用。
# 请务必修改成你自己的路径，否则数据导入会失败哦！
# 示例: base_data_path = "data/"
base_data_path = "your/base/data/path/"

# SQLite 数据库文件的路径。
# 如果是相对路径，将在插件的根目录下创建或查找。
database_path = "database/random_brainhole_data.db"

# (可选) 全局代理配置
# 如果不需要，请保持注释状态或直接删除这两行。
# proxy_host = "127.0.0.1"
# proxy_port = 7890


# --- 造词功能配置 [新功能！] ---
[word_generator]
# 是否开启这个功能
enabled = true

# 用哪个LLM模型来鉴定
llm_model_name = "deepseek-v3"

# LLM的入口地址
llm_base_url = "https://api.siliconflow.cn/v1"

# [必须填写!] 在这里填入你的API密钥，可以填很多个哦！
# 示例: llm_api_keys = ["sk-key1", "sk-key2"]
llm_api_keys = []

# 一次性塞给LLM多少个组合让它品尝？建议不要太大，它会累坏的。
max_combinations_per_request = 100

character_source_strategy = "common"   # 从何处取字？可选值: "db", "common", "full"

# [可选] 各个长度的生成概率，加起来最好等于1哦
[word_generator.generation_probabilities]
"2" = 0.80  # 80%的概率生成两个字的组合
"4" = 0.15  # 15%的概率生成四个字的组合
"3" = 0.05  # 5%的概率生成三个字的组合


# --- 插件配置列表 ---
# [[plugins]] 标记一个插件配置块的开始。
# 您可以为不同的功能定义多个 [[plugins]] 配置块。

[[plugins]]
# 插件模块的友好名称
name = "示例脑洞"
# 位于 'plugins' 子文件夹中的 Python 模块名称 (不含 .py 后缀)
module_name = "brainhole"
# 随机获取信息时调用的函数名
info_function_name = "random_brainhole_info"
# “查词”时用于格式化输出的函数名
format_function_name = "format_brainhole_data"
# 关联的数据库表名
table_name = "brainhole_terms"
# “查词”时搜索的列名
search_column_name = "term"
# 触发关键词
keywords = ["随机脑洞", "脑洞一下", "示例脑洞"]
# 数据文件所在文件夹的名称 (相对于 'base_data_path')
# “随机填词”功能也会使用这个名字作为占位符哦！
folder_name = "脑洞"
# 数据文件的扩展名
file_extensions = [".xlsx"]
# 失败重试次数
retry_attempts = 2
# 最终失败时发送的消息
failure_message = "今天脑洞枯竭了，过会儿再来吧！"

# --- 其他插件配置示例 (保持不变) ---
# [[plugins]]
# name = "示例拼释"
# module_name = "pinshi"
# ... (其他配置)

# [[plugins]]
# name = "蝠汁牌"
# module_name = "fuzhipai"
# ... (其他配置)

# ... 您可以继续在这里添加更多 [[plugins]] 配置块 ...